name: TradingView Scraper

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # หรือเวอร์ชันที่คุณใช้
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest # Action นี้จะจัดการเรื่อง Chrome และ ChromeDriver

      - name: Run scraper script
        run: python scraper.py
        env:
          PYTHONUNBUFFERED: 1 # สำคัญมากสำหรับ real-time logging

      - name: List files after script execution (for debugging)
        if: always() # รันเสมอ
        run: |
          echo "Current directory: $PWD"
          echo "Listing all files in workspace (recursive):"
          ls -R $GITHUB_WORKSPACE
          echo "--- End of file listing ---"

      - name: Upload heatmap HTML results
        uses: actions/upload-artifact@v4
        with:
          name: heatmap-html-report
          path: | # ใช้ multi-line path เพื่อความชัดเจน หรือถ้ามีหลายไฟล์/pattern
            heatmap_output.html
            heatmap_no_data.html # ถ้าคุณสร้างไฟล์นี้ด้วย
          if-no-files-found: warn # หรือ 'error' ถ้าการไม่มีไฟล์นี้ถือว่าล้มเหลว

      - name: Upload heatmap CSV data
        uses: actions/upload-artifact@v4
        with:
          name: heatmap-csv-data
          path: heatmap_data.csv
          if-no-files-found: warn